[build]
builder = "NIXPACKS"
buildCommand = "if [ -d frontend ]; then cd frontend; fi && npm install && npm run build"

[deploy]
startCommand = "if [ -d frontend ]; then cd frontend; fi && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3